### ISSUE TITLE
Incorrect report produced for parametrized features with parallel test execution mode enabled.

### ISSUE THREAD

**Issue by re-l124c41** [renatoathaydes/spock-reports#215] opened 2021-08-18 18:00 UTC
When parallel test execution mode enabled in spock then report produced by spock-reports incorrectly adds all iterations of all features to one feature and marks other features as skipped.

This happens because in parallel mode all features added to `SpecData#featureRuns` list before any of them get executed and then only last feature returned from `SpockReportExtension#currentRun()` when `SpockReportExtension#afterIteration()` called.

This behaviour can be reproduced by running this small project: [https://github.com/re-l124c41/parallel-test-example](https://github.com/re-l124c41/parallel-test-example)

**Comment by renatoathaydes** [comment] 2021-08-24 20:44
@re-l124c41 I think the problem is fixed in dev now... but it's showing the iterations in random order, I will see if there's enough metadata to re-sort the iterations in the final report.

**Comment by renatoathaydes** [comment] 2021-08-24 20:45
Ah, every iteration has an iteration index... it's trivial to sort.

**Comment by re-l124c41** [comment] 2021-08-30 09:54
Hello @renatoathaydes !
Nice to see this fixed! Thank you!
Are you planning to add this to some future release tag?

**Comment by renatoathaydes** [comment] 2021-08-30 21:08
Was waiting for you to confirm it worked in your project. I will release in the next couple of days.

jitpack uses the `publishToMavenLocal` task?! That task shouldn't be triggering signing , I will fix that as well.

**Comment by renatoathaydes** [comment] 2021-08-30 21:22
Fixed... jitpack should work now.

**Comment by re-l124c41** [comment] 2021-09-01 08:18
Sorry I haven't realised you was waiting for me. I was able to build it with jitpack from def-SNAPSHOT and everything working well. 
Thank you)

**Closed** 2021-09-02 16:24 UTC
Labels: bug, ready-for-release

**Comment by renatoathaydes** [comment] 2021-09-02 16:32
I released the fix on version `2.1-groovy-3.0`.
