### ISSUE TITLE
Ignored tests are not recognized as such but are shown as regulary passed test in the report

### ISSUE THREAD

**Issue by SamuelGraf** [renatoathaydes/spock-reports#177] opened 2019-07-02 11:21 UTC
I have the following situation: I want to write a test of the form 
```
@Unroll
def "test for parameter = #parameter "(){
        given:
        ensureSomePremises(parameter)
        
        then:
        expectThatSomethingHolds(parameter)
        
        where:
        parameter << [1,2,3,4,5]
}
```
Now I want to ignore only the test for parameter=2 and parameter=4 (for example I know that there is a bug causing these tests to fail and i reported the bug and now I am only interested in new bugs and don't want to single out the new bugs from the large set of known bugs every time anew). I didn't find a really clean way to do this (unfortunately) so I use this work around (https://stackoverflow.com/questions/33818907/programmatically-skip-a-test-in-spock). This leads to (using JUnits Assume class)

```
@Unroll
def "test for parameter = #parameter "(){
        if (parameter==2 || parameter==4)
             Assume.assumeTrue(false)

        given:
        ensureSomePremises(parameter)
        
        then:
        expectThatSomethingHolds(parameter)
        
        where:
        parameter << [1,2,3,4,5]
}
```
This works great in the sense that executing the tests always skips the tests in which parameter is 2 or 4 and runs the other tests. When run within IntelliJ, IntelliJ recognizes the ignored tests as such and also the test report generated by gradle marks the tests for parameter = 2,4 as skipped. Unfortunately the test reports of spock-reports and geb-spock-reports do not recognize the tests for parameter=2,4 as skipped/ignored but instead marks them as regulary passed even though they were not executed. This is very unfortunate because i prefer the (geb-)spock-reports to the test report generated by gradle. As gradle recognizes the tests (correctly) as ignored I think it should be doable to do so in the (geb-)spock-reports. I would be infinitely grateful and happy if you could fix this bug for me.

Kind regards
Sammy

**Comment by renatoathaydes** [comment] 2019-07-02 16:49
Seems like a duplicate of https://github.com/renatoathaydes/spock-reports/issues/89.
Can you confirm that @SamuelGraf ?

**Comment by SamuelGraf** [comment] 2019-07-03 08:44
Yes it is. Sorry for not checking thoroughly enough.

**Closed** 2020-01-04 10:47 UTC
Labels: duplicate
