### ISSUE TITLE
Encoding problem with TemplateReportCreator

### ISSUE THREAD

**Issue by mfuerstenau** [renatoathaydes/spock-reports#60] opened 2016-04-25 12:50 UTC
I have encoding problems with German characters `äöü`. The Template is UTF-8-encoded. It features words like `Übersicht` (overview) which is correctly written to the report.

But the description from the Spock-tests (the one after `when:`, `given:` etc.) is encoded in ISO-8859-1 due to the fact that this is the default encoding on the system.

I would expect for description to conform to the output-encoding which seems to be UTF-8. Or how about a configuration option in the `.properties`-file.

**Comment by rdmueller** [comment] 2016-04-25 14:08
Why do you encode your tests as iso-8859-1? It should just work if you switch your tests to utf-8...

But I'll also check if I can find another solution. Stay tuned...

**Comment by mfuerstenau** [comment] 2016-04-25 14:35
The source files are UTF-8, the templates are UTF-8, still the descriptions from the tests still get encoded in ISO-8859-1 which is the system default. Other text from the templates ends up correctly as UTF-8. Therefore the result is a mix-up of UTF-8 and some ISO-8859-1, if interpreted as UTF-8 resulting in `?` characters as placeholders (depending on the editor or interpreter).

**Comment by rdmueller** [comment] 2016-04-25 14:51
so, as you use the template report creator, I will use the code from https://github.com/rdmueller/etka15 and try to reproduce the problem...

**Comment by rdmueller** [comment] 2016-04-25 15:10
ok. problem reproduced....

**Comment by mfuerstenau** [comment] 2016-04-25 15:20
This is my template (extract), a JIRA template. It's encoded in UTF-8. The line `Übersicht` is encoded correct in the result, but the `block.text` (`block` results from `Feature.eachFeature(Closure)`) is not correctly encoded in the result.

I could work around if I used: `new String(block.text.getBytes('UTF-8'), 'ISO-8859-1')`
```
<%
    def stats = utils.stats( data )
 %>h2. Bericht für ${data.info.description.className}

h2. Übersicht
...
<%
   for ( block in blocks ) {
 %>* ${block.kind} ${block.text}
<%
   }
%>
...
```

**Comment by rdmueller** [comment] 2016-04-25 15:47
yes, but the workaround is ugly. But I guess, I have a solution. Give me just a moment to verify it. It seems that - alt least in my case - the problem was caused by the encoding of the template file...

**Comment by rdmueller** [comment] 2016-04-25 17:09
I am a little puzzled about the workaround: it doesn't work for me with "ß" and "Ü" but with "ä" and "ü"...
and I couldn't verify my solution :-(

**Comment by rdmueller** [comment] 2016-04-25 17:35
so, the workaround is OS dependent - for windows it is `new String(block.text.getBytes('UTF-8'), 'CP1252')`

**Comment by renatoathaydes** [comment] 2016-04-25 18:48
The text you get when you do `block.text` comes from Spock's `org.spockframework.runtime.model.BlockMetadata#texts()`. I suppose that itself comes from the compiler or Groovy AST Transformer... so it should respect the encoding of the source file... to enforce UTF-8 and avoid issues, you could try to set the java compiler `-encoding` option as explained in the [javac documentation](http://docs.oracle.com/javase/8/docs/technotes/tools/windows/javac.html) or [using Gradle](http://mrhaki.blogspot.se/2012/06/gradle-goodness-set-java-compiler.html), because source code is expected to be in the platform default encoding by default, which in Windows happens to be ISO-8859-1.

**Comment by rdmueller** [comment] 2016-04-25 19:11
thanx. I will give it a try...

**Comment by mfuerstenau** [comment] 2016-04-25 19:30
I'll report my results tomorrow. Right now I'am at home and the project in question is out of reach.

**Comment by rdmueller** [comment] 2016-04-25 20:03
Renato is right - it's a "problem" with gradle and the os specific file encoding. It can be resolved by setting the environment variable `GRADLE_OPTS` to `"-Dfile.encoding=UTF-8"` . If you use the windows powershell, this can be done through
`$env:GRADLE_OPTS="-Dfile.encoding=UTF-8"`

unfortunately, it seems that it can't be set as gradle option, e.g. `gradle "-Dfile.encoding=UTF-8" test`

verified on my test project

**Comment by mfuerstenau** [comment] 2016-04-26 07:12
Setting `-Dfile.encoding=UTF-8` **works**. Adding
```
[compileJava, compileTestJava, compileGroovy, compileTestGroovy]*.options*.encoding = 'UTF-8'
```
**does not work**.

**Comment by mfuerstenau** [comment] 2016-04-26 08:44
I think we can close this Issue now, I posted the last question [at the gradle.org forum](https://discuss.gradle.org/t/is-setting-options-encoding-for-java-groovycompile-task-of-use/17088) as it is a more general gradle question.

**Comment by mfuerstenau** [comment] 2016-04-26 12:54
A **solution** I found: `gradle.properties` in the project dir with:
```
org.gradle.jvmargs='-Dfile.encoding=UTF-8'
```
works even with daemon, as a new instance is created if the existing one(s) differ from JVM args. That way I can check that file into our subversion/git repository and my collegues don't have to fiddle with the build file.

**Comment by renatoathaydes** [comment] 2016-04-26 16:35
@mfuerstenau glad it works now. Thanks for posting back the solution!

**Closed by renatoathaydes** 2016-04-26 16:35 UTC
