### ISSUE TITLE
Vivid report shows neither code nor block text for template report when using test-jar as dependency

### ISSUE THREAD

**Issue by scierniak** [renatoathaydes/spock-reports#144] opened 2018-04-28 12:55 UTC
Hello,

Following Maven Surefire documentation: https://maven.apache.org/plugins/maven-jar-plugin/examples/create-test-jar.html, I am able to generate a tests artifact in a compilation project and to reference it into an execution project.

Into the execution project, we need to add the option dependenciesToScan in order to found the tests and it works fine even the generation of spock report but when using template report, I don't have code block data (kind, type, sourceCode) displayed ? note: same template works fine into compilation project and also default html report works into execution project.

I am using spock-report 1.5.0 and spock 1.1

Extract from my template
<h3>Features:</h3>
<div>
<t able class="table">
    <thead>
        <th>Feature</th>
        <th style="width: 150px;">Result</th>
        <th style="width: 100px;" nowrap>ALM ID</th>
    </thead>
    <tbody>
    <% def index = 0
    features.eachFeature { name, result, blocks, iterations, params ->
    index++
    def aid = amadeus.geb.ahp.utils.ReportUtils.getALMID(data, name)
    //System.out.println("ALM $name: $aid")
    %>
    <tr class='<% if (result == "FAIL" || result == "FAILURE" || result == "ERROR") out << "danger" else if (result == "IGNORED") out << "active" else out << "success" %>' id='0'>
        <td onclick="hideshow('Block<%=index%>');">
            <div id="${name}">
                <a>${name}</a>
            </div>
        </td>
        <td><span>${result}</span></td>
        <td><span><% if (aid) out << "<a href=\"td://hotel.new_businesses.alm-prod/qcbin/TestPlanModule-00000000395028973?EntityType=ITest&EntityID=${aid}\">${aid}</a>" %></span></td>
    </tr>

    <tr id='Block<%=index%>' style='<% if (result == "PASS" || result == "IGNORED") out << "display: none" else out << "display: block" %>'>
        <td>
            <%
            boolean linkDisplayed = true
            for ( block in blocks ) {
            %>
                <div>
                    <span class='block-kind'>${block.kind}</span>
                    <span class='block-text'>${block.text ? block.text : '""'}</span>
                    <%
                    if (block.sourceCode && linkDisplayed) {
                        linkDisplayed = false
                    %>
                        <span style='color: blue;font-size: smaller' onclick="hideshowByClass('source s<%=index%>');">&nbsp;&nbsp;&nbsp;(See source code)</span>
                    <%
                    }
                    %>
                </div>
                <%
                if (block.sourceCode) {
                %>
                    <div class="source s<%=index%>">
                        <%
                        block.sourceCode.each { codeLine ->
                            out << '<p>' << codeLine << '</p>'
                        }
                        %>
                    </div>
                <%
                }
                %>
            <%
            }
            %>
        </td>
    </tr>

Simon

**Comment by scierniak** [comment] 2018-04-30 18:13
FYI, I did the test using geb-spock-report (com.aoe:geb-spock-reports:0.1.5) and I got the same issue

**Comment by renatoathaydes** [comment] 2018-05-01 06:44
When your test is loaded from a jar, the source code is unavailable to spock-reports. Where do you suppose spock-reports would find the source?

**Comment by scierniak** [comment] 2018-05-01 18:04
I agreed for the source code they are not visible unless an improvement is done, but here I don't even see the blocks: kind and text when using the template report.

**Comment by renatoathaydes** [comment] 2018-05-01 20:30
Yeah, block kind and text should be visible even in bytecode, so it should work when a Spec is loaded from a jar... If it works for the default HTML report, it's very strange if it doesn't for templates. I will have a look at what's different (I thought it was exactly the same).

**Comment by scierniak** [comment] 2018-06-25 17:41
any update on this issue ?

**Comment by renatoathaydes** [comment] 2019-04-27 15:59
I reproduced the issue now... looks like tests coming from jars are also not included in the total count of features. I had to add a test sub-class in the project I am testing in order to make the tests from the jar run... I guess you're doing something simlar @scierniak ?

**Comment by scierniak** [comment] 2019-04-29 15:36
To have tests running from jar, I just updated the surefire configuration by adding : dependenciesToScan

<dependenciesToScan>
	<dependency>groupId:artifactId</dependency>
</dependenciesToScan>

**Comment by renatoathaydes** [comment] 2019-04-30 06:43
@scierniak ah, ok... will try that as well.

**Comment by renatoathaydes** [comment] 2019-04-30 19:53
That works now! I also fixed the feature count. Will be included in the upcoming release.

**Closed** 2020-01-04 10:56 UTC
Labels: bug, ready-for-release

**Comment by renatoathaydes** [comment] 2020-01-04 11:15
Fixed in version 1.6.3.
