### ISSUE TITLE
showCodeBlocks fails with NullPointerException

### ISSUE THREAD

**Issue by tloszabno** [renatoathaydes/spock-reports#103] opened 2017-05-18 07:43 UTC
Hello,
Firstly, thanks  for that plugin ! 

Recently I found a problem with showCodeBlocks feature. 
Please look at code in https://github.com/tloszabno/spockpresentation (mvn3+j8) simply run mvn test.
When showCodeBlocks is enabled I getting NullPointerException: https://pastebin.com/PqNPkHwU
This exception occurs for each test. Even when I tried the simpler one with simple asserion (pl.tlos.spock.SpockTest).

Am I configured sth wrongly, or thats a plugin bug ? 
Thanks in advance for answer.

**Comment by renatoathaydes** [comment] 2017-05-18 08:29
I am aware of this bug, but I am not sure in which circumstances it occurs.
Do you run your tests in parallel (this is one suspicion I have, parallel tests break this feature)?
Do you have any other idea about what triggers this bug?

**Comment by tloszabno** [comment] 2017-05-18 08:40
I do not think parallel is problem, even running one single test with one feature it fails. Problem in my code is that It never worked for me (reports).

**Comment by renatoathaydes** [comment] 2017-05-18 16:41
I checked out your project and confirmed the fix I have in the `next` branch works... but this happens because Spock can't get the source of your specs!! Trying to figure out why that is happening.

**Comment by renatoathaydes** [comment] 2017-05-18 16:47
Ah!! I should've known that :) you have your tests in `src/test/java`, not the expected `src/test/groovy`!

You can configure this using this line in the config file:

```
com.athaydes.spockframework.report.testSourceRoots=src/test/java
```

I will make this a little bit more automatic.

**Comment by renatoathaydes** [comment] 2017-05-19 06:48
Fixed in version 1.3.1. I made the documentation clearer about the need to set the directory where the test sources are to be found in case you don't use `src/test/groovy`.

**Closed by renatoathaydes** 2017-05-19 06:48 UTC
Labels: bug

**Comment by tloszabno** [comment] 2017-05-19 06:50
Thanks ! I just test it and all works well :)
