### ISSUE TITLE
Spock 2.0 support

### ISSUE THREAD

**Issue by treyturner** [renatoathaydes/spock-reports#189] opened 2020-02-20 21:46 UTC
Hi there! I'm investigating breakages that will occur when upgrading my test suite to Groovy 3 and Spock 2.0. Though I'm sure you've anticipated this, Spock does seem to have some changes which causes spock-reports to throw.

We're in no rush to upgrade, as the reporting we've established via spock-reports is more important than the new features, but I thought I'd put this on the radar as it would be nice to eventually receive these benefits and stay up to date with their developments.

Thanks for your time!

Here's the stacktrace thrown using Groovy 3.0.1, Spock 2.0-M2, and Gradle 6.2 within IDEA 2019.3.3:
```
No such property: description for class: org.spockframework.runtime.model.SpecInfo
groovy.lang.MissingPropertyException: No such property: description for class: org.spockframework.runtime.model.SpecInfo
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
	at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:65)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:329)
	at com.athaydes.spockframework.report.util.Utils.getSpecClassName(Utils.groovy:195)
	at com.athaydes.spockframework.report.util.Utils$getSpecClassName$1.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:231)
	at com.athaydes.spockframework.report.util.Utils.getSpecClassName(Utils.groovy:191)
	at com.athaydes.spockframework.report.util.Utils$getSpecClassName$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at com.athaydes.spockframework.report.SpecInfoListener.beforeSpec(SpockReportExtension.groovy:127)
	at org.spockframework.runtime.MasterRunListener.beforeSpec(MasterRunListener.java:29)
	at org.spockframework.runtime.MasterRunSupervisor.beforeSpec(MasterRunSupervisor.java:24)
	at org.spockframework.runtime.PlatformSpecRunner.runSpec(PlatformSpecRunner.java:52)
	at org.spockframework.runtime.SpecNode.around(SpecNode.java:61)
	at org.spockframework.runtime.SpecNode.around(SpecNode.java:8)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by renatoathaydes** [comment] 2020-02-21 16:59
Thanks for pointing it out! I have been definitely thinking about migrating to Groovy 3 and it's good to know Spock itself is already preparing as well!

I will try soon to do the upgrade and release some RC versions!

**Comment by renatoathaydes** [comment] 2020-03-09 20:08
I think I'm past the hardest part of the upgrade now.
You can keep track of progress on this branch:

https://github.com/renatoathaydes/spock-reports/commits/spock2

Would actually be very nice if someone could help me test we do not introduce any bugs as things have been changed in several subtle ways.

**Comment by SohamJ** [comment] 2020-05-15 12:27
> I think I'm past the hardest part of the upgrade now.
> You can keep track of progress on this branch:
> 
> https://github.com/renatoathaydes/spock-reports/commits/spock2
> 
> Would actually be very nice if someone could help me test we do not introduce any bugs as things have been changed in several subtle ways.

Hi @renatoathaydes Thanks for adding the support for Groovy3/Spock2.0. I tested this branch and got the below error - 
```
Cannot get property 'info' on null object
java.lang.NullPointerException: Cannot get property 'info' on null object
	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:192)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:46)
	at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.callGetProperty(GetEffectivePogoPropertySite.java:45)
	at com.athaydes.spockframework.report.SpecInfoListener.afterSpec(SpockReportExtension.groovy:170)
	at org.spockframework.runtime.MasterRunListener.afterSpec(MasterRunListener.java:64)
	at org.spockframework.runtime.MasterRunSupervisor.afterSpec(MasterRunSupervisor.java:128)
	at org.spockframework.runtime.PlatformSpecRunner.runSpec(PlatformSpecRunner.java:54)
	at org.spockframework.runtime.SpecNode.around(SpecNode.java:61)
	at org.spockframework.runtime.SpecNode.around(SpecNode.java:8)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
```

my build info -
spock-reports jar - spock-reports-2.0-RC1.jar based on [this](https://github.com/renatoathaydes/spock-reports/commits/spock2) branch
Groovy - 3.0.2
Gradle - 6.3
spockCoreGroovyVersion - '2.0-M2-groovy-3.0'
junitVersion - 4.13

The `executionError` is happening only for one Spec, rest of the Spec classes are running fine. Although all pretty much have simple use of Shared, when and then.

Please let me know if I should provide any additional info

**Comment by renatoathaydes** [comment] 2020-05-15 15:25
Spock-reports's own tests had stopped running because of the upgrade... I've added now the thing that makes JUnit5 tests (hence Spock2) tests run:

```groovy
test {
    useJUnitPlatform()
}
```

It picks up this problem... There's only a few tests failing... will fix and publish a new version as soon as I can.

**Comment by renatoathaydes** [comment] 2020-05-15 15:42
Spock is behaving strangely. It's calling `beforeSpec` twice before calling `afterSpec`, which is why this error is happening. It never did that before, it's supposed to always call `beforeSpec`, then `afterSpec`, and then again `beforeSpec` and so on...

There's also other bugs in Spock: it is throwing a nullpointer Exception when I call `NodeInfo::getAnnotation(annotationType)` in some cases, and in others, it's returning something that's not an `Annotation`, despite the method's signature being `public <T extends Annotation> T getAnnotation(Class<T> clazz)` (it returns a generated class like `SpecInfo$$EnhancerByCGLIB$$e6d57ec6`, but that should implement the inferface anyway).

I might have to report these to Spock if they don't know about them yet, as I can't fix these in spock-reports (I could catch errors, but that would just hide the issue).

**Comment by renatoathaydes** [comment] 2020-05-15 17:53
I was able to get everything working after all!!

It was mostly my tests that needed modifications... the main code itself is working mostly fine! I've got GitHub Actions testing my PRs in Java 8 and 11 on all Operating Systems, so I am pretty confident spock-reports is working now. Releasing a new version. It's already merged to master.

**Comment by SohamJ** [comment] 2020-05-18 10:41
Confirming that it is working fine :) Thank you, @renatoathaydes!

**Closed** 2020-05-18 11:09 UTC
Labels: enhancement, in progress

**Comment by lavigne** [comment] 2021-11-10 22:08
@renatoathaydes were you actually able to get the "No such property" exception mentioned by @treyturner to go away?  I have recently upgraded from Spock 1.3/Groovy 2.5 to Spock 2/Groovy 3 and I get the same exception.  My tests run fine, but my console gets filled with stack traces about this missing property.  I've looked at the `SpecInfo` class and it indeed doesn't have a `description` property on the newer version of the class found in `spock-core-2.0-groovy-3.0.jar`, where as `spock-core-1.3-groovy-2.5.jar` has a version of `SpecInfo` that does have a `description` property.  So this seems like a clear error message and it's just a bug in the spock-reports framework where it's trying to reference a property on the `org.spockframework.runtime.model.SpecInfo` class that has been removed in the newer version of the class.  Am I missing something here?  I can't find much information on this issue so it seems like I must have something configured incorrectly or else I would expect to find many people having this same problem.  Any advice you can lend would be greatly appreciated. Here is the exception message I'm talking about:

```
No such property: description for class: org.spockframework.runtime.model.SpecInfo
groovy.lang.MissingPropertyException: No such property: description for class: org.spockframework.runtime.model.SpecInfo
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
	at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:65)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:329)
	at com.athaydes.spockframework.report.util.Utils.getSpecClassName(Utils.groovy:195)
	at com.athaydes.spockframework.report.util.Utils$getSpecClassName$1.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:231)
	at com.athaydes.spockframework.report.util.Utils.getSpecClassName(Utils.groovy:191)
	at com.athaydes.spockframework.report.util.Utils$getSpecClassName$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at com.athaydes.spockframework.report.SpecInfoListener.beforeSpec(SpockReportExtension.groovy:127)
	at org.spockframework.runtime.MasterRunListener.beforeSpec(MasterRunListener.java:29)
	at org.spockframework.runtime.MasterRunSupervisor.beforeSpec(MasterRunSupervisor.java:24)
	at org.spockframework.runtime.PlatformSpecRunner.runSpec(PlatformSpecRunner.java:52)
	at org.spockframework.runtime.SpecNode.around(SpecNode.java:61)
	at org.spockframework.runtime.SpecNode.around(SpecNode.java:8)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by renatoathaydes** [comment] 2021-11-10 22:41
@lavigne your stacktrace shows the problem coming from `Utils.getSpecClassName(Utils.groovy:195)`.

In the current versions of spock-reports, this line is not inside this function.

https://github.com/renatoathaydes/spock-reports/blob/2.1.1-groovy-3.0/src/main/groovy/com/athaydes/spockframework/report/util/Utils.groovy#L195

I can't even find a version where this line is inside that function... I suggest that you verify you're indeed using the latest version of spock-reports: `2.1.1-groovy-3.0`.

**Comment by lavigne** [comment] 2021-11-10 22:55
@renatoathaydes Thank you for the quick reply.  I did actually try upgrading to `2.1.1-groovy-3.0` before posting this message. 
 However I was still seeing the issue so I decided to post here for help.

**Comment by lavigne** [comment] 2021-11-11 00:06
@renatoathaydes Upon closer inspection of the stack trace, the one I'm getting is different than the one originally posted in this issue.  The first part of the call stack is the same but when I look further down in the stack I can see my issue is originating with the `TemplateReportCreator` class, not the `Utils` class.  Sorry that I missed that.  Here is the actual stack trace I am getting:

```
2021-11-10 18:02:03.434  WARN   --- [           main] c.a.s.r.template.TemplateReportCreator   : Unexpected error creating report

groovy.lang.MissingPropertyException: No such property: description for class: org.spockframework.runtime.model.SpecInfo
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
        at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:65)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:329)
        at groovy.tmp.templates.GStringTemplateScript1$_getTemplate_closure1.doCall(GStringTemplateScript1.groovy:5)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure$WritableClosure.writeTo(Closure.java:912)
        at groovy.lang.Closure$WritableClosure.toString(Closure.java:1039)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:73)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
        at com.athaydes.spockframework.report.template.TemplateReportCreator.reportFor(TemplateReportCreator.groovy:126)
        at com.athaydes.spockframework.report.template.TemplateReportCreator$reportFor.callCurrent(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
```

**Comment by renatoathaydes** [comment] 2021-11-11 16:01
What's the template you're using? I checked the default one shipped with spock-reports and that works fine. If you use a custom template, I'm afraid you need to change that yourself. `SpecInfo` is a Spock class and as they've changed it, I expect all templates using that directly will need to be updated after upgrading.

**Comment by lavigne** [comment] 2021-11-11 16:40
@renatoathaydes Thank you, the template was the issue.  I apologize, I've never set up Spock/Spock Reporting and inherited this project, so I didn't realize we were using a custom template.

**Comment by ingoschaal** [comment] 2023-09-19 15:05
Hi @renatoathaydes 
thanks for the help with the problems so far

i have a similar problem
after updating from org.spockframework:spock-core:1.3-groovy-2.4 to org.spockframework:spock-core:2.3-groovy-3.0
i also get the error 
WARN com.athaydes.spockframework.report.template.TemplateReportCreator - Unexpected error creating report
groovy.lang.MissingPropertyException: No such property: description for class: org.spockframework.runtime.model.SpecInfo

we modified the provided template shipped with spock-reports a little bit, it always worked since then very fine.
Now i use the original template shipped with spock-reports, (I found it in the wiki page, hope this is the right one)  but it is always the same error.
Maybe you have an idea what the problem is.
I am grateful for any advice

Ingo

**Comment by ingoschaal** [comment] 2023-09-20 07:33
Hi again,
after a deeper look into the templates i saw that 'description' is accessed here
https://github.com/renatoathaydes/spock-reports/wiki/AsciiDoc-Spec-Template

`<%  def fmt = new com.athaydes.spockframework.report.internal.StringFormatHelper()
    def stats = com.athaydes.spockframework.report.util.Utils.stats( data )
 %>== Report for ``${data.info.description.className}`
 
 i change this
`${data.info.description.className}`
to 
`${data.info.name}`


maybe you can update this template
thank you for the great library and thank you

**Comment by renatoathaydes** [comment] 2023-09-20 16:57
Hi @ingoschaal , I do not maintain the adoc templates, sorry.
Someone posted an updated report here: https://github.com/renatoathaydes/spock-reports/issues/16#issuecomment-1719522885

Does that help you? I think you can edit the wiki yourself if you want! If you can't, let me know if the above works or whether I should use the one you posted and I can update it later.

**Comment by ingoschaal** [comment] 2023-09-21 05:41
Hi
thanks for the tip, yes I think this template should work.
I have meanwhile fixed our customized template and it works then.
Maybe Bertrand Florat can update the wiki with his fixed version.
